@REM This batch file has been generated by the IAR Embedded Workbench
@REM C-SPY Debugger, as an aid to preparing a command line for running
@REM the cspybat command line utility using the appropriate settings.
@REM
@REM Note that this file is generated every time a new debug session
@REM is initialized, so you may want to move or rename the file before
@REM making changes.
@REM
@REM You can launch cspybat by typing the name of this batch file followed
@REM by the name of the debug file (usually an ELF/DWARF or UBROF file).
@REM
@REM Read about available command line parameters in the C-SPY Debugging
@REM Guide. Hints about additional command line parameters that may be
@REM useful in specific cases:
@REM   --download_only   Downloads a code image without starting a debug
@REM                     session afterwards.
@REM   --silent          Omits the sign-on message.
@REM   --timeout         Limits the maximum allowed execution time.
@REM 


@echo off 

if not "%~1" == "" goto debugFile 

@echo on 

"D:\IAR8_0ARM\common\bin\cspybat" -f "G:\单片机资料\历史程序\ov7670\oc7670_1\IAR_TO_ARM_TEST_0\settings\STM32F407_TEST_0.Debug.general.xcl" --backend -f "G:\单片机资料\历史程序\ov7670\oc7670_1\IAR_TO_ARM_TEST_0\settings\STM32F407_TEST_0.Debug.driver.xcl" 

@echo off 
goto end 

:debugFile 

@echo on 

"D:\IAR8_0ARM\common\bin\cspybat" -f "G:\单片机资料\历史程序\ov7670\oc7670_1\IAR_TO_ARM_TEST_0\settings\STM32F407_TEST_0.Debug.general.xcl" "--debug_file=%~1" --backend -f "G:\单片机资料\历史程序\ov7670\oc7670_1\IAR_TO_ARM_TEST_0\settings\STM32F407_TEST_0.Debug.driver.xcl" 

@echo off 
:end